# El método de k-means

In [2]:
import numpy as np

In [3]:
data = np.random.random(90).reshape(30,3)# reshape(30,3) reorganiza en 30 filas y 3 columnas
data

array([[0.48514984, 0.02655094, 0.58578618],
       [0.09300462, 0.11709263, 0.68424208],
       [0.53287514, 0.18877692, 0.56941547],
       [0.1857435 , 0.69527817, 0.36172618],
       [0.95538228, 0.18420636, 0.41819175],
       [0.78885824, 0.17814084, 0.83426811],
       [0.31965536, 0.45950874, 0.76801465],
       [0.52208765, 0.69424498, 0.42559787],
       [0.2294964 , 0.16030444, 0.83272993],
       [0.90424064, 0.82671329, 0.98715722],
       [0.18715188, 0.14701134, 0.96428257],
       [0.13303723, 0.70555229, 0.24601589],
       [0.34116449, 0.52906769, 0.4570362 ],
       [0.25550392, 0.27884239, 0.83907017],
       [0.44919434, 0.20332154, 0.59032831],
       [0.63004197, 0.81572449, 0.88444375],
       [0.21083782, 0.59423494, 0.77425876],
       [0.18484538, 0.57743373, 0.28397077],
       [0.70936379, 0.26407341, 0.1514361 ],
       [0.39649673, 0.23950352, 0.21888071],
       [0.23452674, 0.71322534, 0.63299204],
       [0.15855555, 0.14232056, 0.85838671],
       [0.

In [5]:
c1 = np.random.choice(range(len(data)))# choice : escoje al Azar
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.18715188, 0.14701134, 0.96428257],
       [0.65389144, 0.56076822, 0.21531305]])

In [6]:
from scipy.cluster.vq import vq

In [7]:
clusters = vq(data, clust_centers)
clusters

(array([0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
        0, 1, 1, 1, 1, 0, 1, 1], dtype=int32),
 array([0.49656118, 0.29695372, 0.52648738, 0.50861795, 0.52331188,
        0.61637922, 0.39208787, 0.28179423, 0.13883754, 0.85389983,
        0.        , 0.54147409, 0.39652635, 0.19424102, 0.46008574,
        0.71645474, 0.48649668, 0.47433724, 0.30852108, 0.41167435,
        0.61120018, 0.10978928, 0.43309569, 0.77837891, 0.58021724,
        0.76652311, 0.48645254, 0.50166445, 0.7563061 , 0.        ]))

In [6]:
labels = clusters[0]
labels

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1])

In [11]:
import plotly.plotly as py
import plotly.graph_objs as go
import plotly.offline as ply

ModuleNotFoundError: No module named 'plotly'

In [ ]:
x = []
y = []
z = []
x2 = []
y2 = []
z2 = []

for i in range(0, len(labels)):
    if(labels[i] == 0):
        x.append(data[i,0])
        y.append(data[i,1])
        z.append(data[i,2])
        
    else:
        x2.append(data[i,0])
        y2.append(data[i,1])
        z2.append(data[i,2])

cluster1 = go.Scatter3d(
    x=x,
    y=y,
    z=z,
    mode='markers',
    marker=dict(
        size=12,
        line=dict(
            color='rgba(217, 217, 217, 0.14)',
            width=0.5
        ),
        opacity=0.9
    ),
    name="Cluster 0"
)


cluster2 = go.Scatter3d(
    x=x2,
    y=y2,
    z=z2,
    mode='markers',
    marker=dict(
        color='rgb(127, 127, 127)',
        size=12,
        symbol='circle',
        line=dict(
            color='rgb(204, 204, 204)',
            width=1
        ),
        opacity=0.9
    ),
    name="Cluster 1"
)
data2 = [cluster1, cluster2]
layout = go.Layout(
    margin=dict(
        l=0,
        r=0,
        b=0,
        t=30
    )
)

fig = go.Figure(data=data2, layout=layout)
ply.plot(fig, filename='Clusters')


In [8]:
from scipy.cluster.vq import kmeans

In [9]:
kmeans(data, clust_centers)

(array([[0.36900498, 0.18051081, 0.75264003],
        [0.47049132, 0.62484834, 0.52725286]]),
 0.3559377781099935)

In [10]:
kmeans(data, 2)

(array([[0.37456128, 0.38264899, 0.54986831],
        [0.72687158, 0.85830252, 0.91002739]]),
 0.3497416094414412)